// <auto-generated />
using System;
using ASP1.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209112103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.HasIndex("PartyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            Age = 45,
                            Description = "Candidat PSD la Camera Deputaților.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/1.jpg",
                            Name = "Ion Popescu",
                            PartyId = 1,
                            Position = "Deputat"
                        },
                        new
                        {
                            CandidateId = 2,
                            Age = 52,
                            Description = "Candidat PNL la Senat.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/2.jpg",
                            Name = "Maria Ionescu",
                            PartyId = 2,
                            Position = "Senator"
                        },
                        new
                        {
                            CandidateId = 3,
                            Age = 38,
                            Description = "Candidat USR la Camera Deputaților.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/3.jpg",
                            Name = "Andrei Vasilescu",
                            PartyId = 3,
                            Position = "Deputat"
                        },
                        new
                        {
                            CandidateId = 4,
                            Age = 41,
                            Description = "Candidat AUR la Senat.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/4.jpg",
                            Name = "Elena Dumitru",
                            PartyId = 4,
                            Position = "Senator"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Election", b =>
                {
                    b.Property<int>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ElectionId");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            ElectionId = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Description = "Elections for mayors, county council presidents, and local council members across all Romanian counties and municipalities.",
                            EndDate = new DateTime(2026, 1, 3, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            IsActive = true,
                            StartDate = new DateTime(2025, 12, 4, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Title = "Local Elections 2024",
                            Type = 1
                        },
                        new
                        {
                            ElectionId = 2,
                            CreatedAt = new DateTime(2025, 11, 24, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Description = "Elections for members of the Chamber of Deputies and the Senate of Romania.",
                            EndDate = new DateTime(2025, 12, 29, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            IsActive = true,
                            StartDate = new DateTime(2025, 11, 29, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Title = "Parliamentary Elections 2024",
                            Type = 2
                        },
                        new
                        {
                            ElectionId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Description = "Election for the President of Romania. Citizens vote for the head of state who serves a five-year term.",
                            EndDate = new DateTime(2026, 1, 5, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            IsActive = true,
                            StartDate = new DateTime(2025, 12, 6, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Title = "Presidential Elections 2024",
                            Type = 3
                        },
                        new
                        {
                            ElectionId = 4,
                            CreatedAt = new DateTime(2025, 11, 27, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Description = "National referendum on proposed constitutional amendments regarding judicial reform and anti-corruption measures.",
                            EndDate = new DateTime(2026, 1, 1, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            IsActive = true,
                            StartDate = new DateTime(2025, 12, 2, 11, 21, 3, 241, DateTimeKind.Utc).AddTicks(8517),
                            Title = "Constitutional Referendum 2024",
                            Type = 4
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            Description = "Partidul Social Democrat",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/6/6e/Logo_PSD_2020.png",
                            Name = "PSD"
                        },
                        new
                        {
                            PartyId = 2,
                            Description = "Partidul Național Liberal",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Logo_PNL_2014.png",
                            Name = "PNL"
                        },
                        new
                        {
                            PartyId = 3,
                            Description = "Uniunea Salvați România",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/Logo_USR_2020.png",
                            Name = "USR"
                        },
                        new
                        {
                            PartyId = 4,
                            Description = "Alianța pentru Unirea Românilor",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2d/Logo_AUR_2020.png",
                            Name = "AUR"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("ASP1.Backend.Domain.Entities.Party", "Party")
                        .WithMany("Candidates")
                        .HasForeignKey("PartyId");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Party", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
