// <auto-generated />
using System;
using ASP1.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209120026_AddVotingSystem")]
    partial class AddVotingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.HasIndex("PartyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            Age = 45,
                            Description = "Candidat PSD la Camera Deputaților.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/1.jpg",
                            Name = "Ion Popescu",
                            PartyId = 1,
                            Position = "Deputat"
                        },
                        new
                        {
                            CandidateId = 2,
                            Age = 52,
                            Description = "Candidat PNL la Senat.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/2.jpg",
                            Name = "Maria Ionescu",
                            PartyId = 2,
                            Position = "Senator"
                        },
                        new
                        {
                            CandidateId = 3,
                            Age = 38,
                            Description = "Candidat USR la Camera Deputaților.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/3.jpg",
                            Name = "Andrei Vasilescu",
                            PartyId = 3,
                            Position = "Deputat"
                        },
                        new
                        {
                            CandidateId = 4,
                            Age = 41,
                            Description = "Candidat AUR la Senat.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/4.jpg",
                            Name = "Elena Dumitru",
                            PartyId = 4,
                            Position = "Senator"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.County", b =>
                {
                    b.Property<int>("CountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EligibleVoters")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountyId");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            CountyId = 1,
                            Code = "AB",
                            EligibleVoters = 250000,
                            Name = "Alba"
                        },
                        new
                        {
                            CountyId = 2,
                            Code = "AR",
                            EligibleVoters = 380000,
                            Name = "Arad"
                        },
                        new
                        {
                            CountyId = 3,
                            Code = "AG",
                            EligibleVoters = 520000,
                            Name = "Argeș"
                        },
                        new
                        {
                            CountyId = 4,
                            Code = "BC",
                            EligibleVoters = 580000,
                            Name = "Bacău"
                        },
                        new
                        {
                            CountyId = 5,
                            Code = "BH",
                            EligibleVoters = 480000,
                            Name = "Bihor"
                        },
                        new
                        {
                            CountyId = 6,
                            Code = "BN",
                            EligibleVoters = 250000,
                            Name = "Bistrița-Năsăud"
                        },
                        new
                        {
                            CountyId = 7,
                            Code = "BT",
                            EligibleVoters = 380000,
                            Name = "Botoșani"
                        },
                        new
                        {
                            CountyId = 8,
                            Code = "BV",
                            EligibleVoters = 480000,
                            Name = "Brașov"
                        },
                        new
                        {
                            CountyId = 9,
                            Code = "BR",
                            EligibleVoters = 280000,
                            Name = "Brăila"
                        },
                        new
                        {
                            CountyId = 10,
                            Code = "B",
                            EligibleVoters = 1800000,
                            Name = "București"
                        },
                        new
                        {
                            CountyId = 11,
                            Code = "BZ",
                            EligibleVoters = 420000,
                            Name = "Buzău"
                        },
                        new
                        {
                            CountyId = 12,
                            Code = "CS",
                            EligibleVoters = 280000,
                            Name = "Caraș-Severin"
                        },
                        new
                        {
                            CountyId = 13,
                            Code = "CJ",
                            EligibleVoters = 620000,
                            Name = "Cluj"
                        },
                        new
                        {
                            CountyId = 14,
                            Code = "CT",
                            EligibleVoters = 620000,
                            Name = "Constanța"
                        },
                        new
                        {
                            CountyId = 15,
                            Code = "CV",
                            EligibleVoters = 180000,
                            Name = "Covasna"
                        },
                        new
                        {
                            CountyId = 16,
                            Code = "DB",
                            EligibleVoters = 480000,
                            Name = "Dâmbovița"
                        },
                        new
                        {
                            CountyId = 17,
                            Code = "DJ",
                            EligibleVoters = 620000,
                            Name = "Dolj"
                        },
                        new
                        {
                            CountyId = 18,
                            Code = "GL",
                            EligibleVoters = 480000,
                            Name = "Galați"
                        },
                        new
                        {
                            CountyId = 19,
                            Code = "GR",
                            EligibleVoters = 250000,
                            Name = "Giurgiu"
                        },
                        new
                        {
                            CountyId = 20,
                            Code = "GJ",
                            EligibleVoters = 320000,
                            Name = "Gorj"
                        },
                        new
                        {
                            CountyId = 21,
                            Code = "HR",
                            EligibleVoters = 280000,
                            Name = "Harghita"
                        },
                        new
                        {
                            CountyId = 22,
                            Code = "HD",
                            EligibleVoters = 380000,
                            Name = "Hunedoara"
                        },
                        new
                        {
                            CountyId = 23,
                            Code = "IL",
                            EligibleVoters = 250000,
                            Name = "Ialomița"
                        },
                        new
                        {
                            CountyId = 24,
                            Code = "IS",
                            EligibleVoters = 720000,
                            Name = "Iași"
                        },
                        new
                        {
                            CountyId = 25,
                            Code = "IF",
                            EligibleVoters = 380000,
                            Name = "Ilfov"
                        },
                        new
                        {
                            CountyId = 26,
                            Code = "MM",
                            EligibleVoters = 420000,
                            Name = "Maramureș"
                        },
                        new
                        {
                            CountyId = 27,
                            Code = "MH",
                            EligibleVoters = 220000,
                            Name = "Mehedinți"
                        },
                        new
                        {
                            CountyId = 28,
                            Code = "MS",
                            EligibleVoters = 480000,
                            Name = "Mureș"
                        },
                        new
                        {
                            CountyId = 29,
                            Code = "NT",
                            EligibleVoters = 420000,
                            Name = "Neamț"
                        },
                        new
                        {
                            CountyId = 30,
                            Code = "OT",
                            EligibleVoters = 420000,
                            Name = "Olt"
                        },
                        new
                        {
                            CountyId = 31,
                            Code = "PH",
                            EligibleVoters = 720000,
                            Name = "Prahova"
                        },
                        new
                        {
                            CountyId = 32,
                            Code = "SJ",
                            EligibleVoters = 200000,
                            Name = "Sălaj"
                        },
                        new
                        {
                            CountyId = 33,
                            Code = "SM",
                            EligibleVoters = 320000,
                            Name = "Satu Mare"
                        },
                        new
                        {
                            CountyId = 34,
                            Code = "SB",
                            EligibleVoters = 380000,
                            Name = "Sibiu"
                        },
                        new
                        {
                            CountyId = 35,
                            Code = "SV",
                            EligibleVoters = 580000,
                            Name = "Suceava"
                        },
                        new
                        {
                            CountyId = 36,
                            Code = "TR",
                            EligibleVoters = 320000,
                            Name = "Teleorman"
                        },
                        new
                        {
                            CountyId = 37,
                            Code = "TM",
                            EligibleVoters = 620000,
                            Name = "Timiș"
                        },
                        new
                        {
                            CountyId = 38,
                            Code = "TL",
                            EligibleVoters = 200000,
                            Name = "Tulcea"
                        },
                        new
                        {
                            CountyId = 39,
                            Code = "VL",
                            EligibleVoters = 320000,
                            Name = "Vâlcea"
                        },
                        new
                        {
                            CountyId = 40,
                            Code = "VS",
                            EligibleVoters = 380000,
                            Name = "Vaslui"
                        },
                        new
                        {
                            CountyId = 41,
                            Code = "VN",
                            EligibleVoters = 320000,
                            Name = "Vrancea"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Election", b =>
                {
                    b.Property<int>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ElectionId");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            ElectionId = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Description = "Elections for mayors, county council presidents, and local council members across all Romanian counties and municipalities.",
                            EndDate = new DateTime(2026, 1, 3, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            IsActive = true,
                            StartDate = new DateTime(2025, 12, 4, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Title = "Local Elections 2024",
                            Type = 1
                        },
                        new
                        {
                            ElectionId = 2,
                            CreatedAt = new DateTime(2025, 11, 24, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Description = "Elections for members of the Chamber of Deputies and the Senate of Romania.",
                            EndDate = new DateTime(2025, 12, 29, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            IsActive = true,
                            StartDate = new DateTime(2025, 11, 29, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Title = "Parliamentary Elections 2024",
                            Type = 2
                        },
                        new
                        {
                            ElectionId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Description = "Election for the President of Romania. Citizens vote for the head of state who serves a five-year term.",
                            EndDate = new DateTime(2026, 1, 5, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            IsActive = true,
                            StartDate = new DateTime(2025, 12, 6, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Title = "Presidential Elections 2024",
                            Type = 3
                        },
                        new
                        {
                            ElectionId = 4,
                            CreatedAt = new DateTime(2025, 11, 27, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Description = "National referendum on proposed constitutional amendments regarding judicial reform and anti-corruption measures.",
                            EndDate = new DateTime(2026, 1, 1, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            IsActive = true,
                            StartDate = new DateTime(2025, 12, 2, 12, 0, 26, 305, DateTimeKind.Utc).AddTicks(3016),
                            Title = "Constitutional Referendum 2024",
                            Type = 4
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.ElectionCandidate", b =>
                {
                    b.Property<int>("ElectionCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionCandidateId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.HasKey("ElectionCandidateId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.ToTable("ElectionCandidates");

                    b.HasData(
                        new
                        {
                            ElectionCandidateId = 1,
                            CandidateId = 1,
                            ElectionId = 2
                        },
                        new
                        {
                            ElectionCandidateId = 2,
                            CandidateId = 2,
                            ElectionId = 2
                        },
                        new
                        {
                            ElectionCandidateId = 3,
                            CandidateId = 3,
                            ElectionId = 2
                        },
                        new
                        {
                            ElectionCandidateId = 4,
                            CandidateId = 4,
                            ElectionId = 2
                        },
                        new
                        {
                            ElectionCandidateId = 5,
                            CandidateId = 1,
                            ElectionId = 3
                        },
                        new
                        {
                            ElectionCandidateId = 6,
                            CandidateId = 2,
                            ElectionId = 3
                        },
                        new
                        {
                            ElectionCandidateId = 7,
                            CandidateId = 3,
                            ElectionId = 3
                        },
                        new
                        {
                            ElectionCandidateId = 8,
                            CandidateId = 4,
                            ElectionId = 3
                        },
                        new
                        {
                            ElectionCandidateId = 9,
                            CandidateId = 1,
                            ElectionId = 1
                        },
                        new
                        {
                            ElectionCandidateId = 10,
                            CandidateId = 2,
                            ElectionId = 1
                        },
                        new
                        {
                            ElectionCandidateId = 11,
                            CandidateId = 3,
                            ElectionId = 1
                        },
                        new
                        {
                            ElectionCandidateId = 12,
                            CandidateId = 4,
                            ElectionId = 1
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            Description = "Partidul Social Democrat",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/6/6e/Logo_PSD_2020.png",
                            Name = "PSD"
                        },
                        new
                        {
                            PartyId = 2,
                            Description = "Partidul Național Liberal",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Logo_PNL_2014.png",
                            Name = "PNL"
                        },
                        new
                        {
                            PartyId = 3,
                            Description = "Uniunea Salvați România",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/Logo_USR_2020.png",
                            Name = "USR"
                        },
                        new
                        {
                            PartyId = 4,
                            Description = "Alianța pentru Unirea Românilor",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2d/Logo_AUR_2020.png",
                            Name = "AUR"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VoteId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CountyId");

                    b.HasIndex("ElectionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("ASP1.Backend.Domain.Entities.Party", "Party")
                        .WithMany("Candidates")
                        .HasForeignKey("PartyId");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.ElectionCandidate", b =>
                {
                    b.HasOne("ASP1.Backend.Domain.Entities.Candidate", "Candidate")
                        .WithMany("ElectionCandidates")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP1.Backend.Domain.Entities.Election", "Election")
                        .WithMany("ElectionCandidates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Vote", b =>
                {
                    b.HasOne("ASP1.Backend.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP1.Backend.Domain.Entities.County", "County")
                        .WithMany("Votes")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP1.Backend.Domain.Entities.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("County");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("ElectionCandidates");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.County", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Election", b =>
                {
                    b.Navigation("ElectionCandidates");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Party", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
