// <auto-generated />
using System;
using ASP1.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.HasIndex("PartyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            Age = 45,
                            Description = "Candidat PSD la Camera Deputaților.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/1.jpg",
                            Name = "Ion Popescu",
                            PartyId = 1,
                            Position = "Deputat"
                        },
                        new
                        {
                            CandidateId = 2,
                            Age = 52,
                            Description = "Candidat PNL la Senat.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/2.jpg",
                            Name = "Maria Ionescu",
                            PartyId = 2,
                            Position = "Senator"
                        },
                        new
                        {
                            CandidateId = 3,
                            Age = 38,
                            Description = "Candidat USR la Camera Deputaților.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/3.jpg",
                            Name = "Andrei Vasilescu",
                            PartyId = 3,
                            Position = "Deputat"
                        },
                        new
                        {
                            CandidateId = 4,
                            Age = 41,
                            Description = "Candidat AUR la Senat.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/4.jpg",
                            Name = "Elena Dumitru",
                            PartyId = 4,
                            Position = "Senator"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            Description = "Partidul Social Democrat",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/6/6e/Logo_PSD_2020.png",
                            Name = "PSD"
                        },
                        new
                        {
                            PartyId = 2,
                            Description = "Partidul Național Liberal",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Logo_PNL_2014.png",
                            Name = "PNL"
                        },
                        new
                        {
                            PartyId = 3,
                            Description = "Uniunea Salvați România",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/Logo_USR_2020.png",
                            Name = "USR"
                        },
                        new
                        {
                            PartyId = 4,
                            Description = "Alianța pentru Unirea Românilor",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2d/Logo_AUR_2020.png",
                            Name = "AUR"
                        });
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("ASP1.Backend.Domain.Entities.Party", "Party")
                        .WithMany("Candidates")
                        .HasForeignKey("PartyId");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("ASP1.Backend.Domain.Entities.Party", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
